export const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(v,c)=>v==null?'—':new Intl.NumberFormat('de-DE',{style:'currency',currency:c,maximumFractionDigits:2}).format(v);
const pct=v=>v==null?'—':new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:1}).format(v);
const number=v=>v==null?'—':new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(v);
const shortDate=d=>d.slice(8)+'.'+d.slice(5,7)+'.';
const delta=(v,unit='')=>v==null?'Nicht vergleichbar':`${v>=0?'+':''}${unit==='pp'?(v*100).toFixed(1)+' pp':pct(v)}`;
export function comparisonView(a,currency) {
 const specs=[['Umsatz','revenue',v=>money(v,currency)],['Deckungsbeitrag','profit',v=>money(v,currency)],['Einheiten','units',number],['Erstattungsquote','refundRate',pct]];
 return `<section class="panel comparison-panel"><div class="panel-heading"><h2>Was hat sich verändert?</h2><span>${a.previous?`${shortDate(a.options.start)}–${shortDate(a.options.end)} vs. ${shortDate(a.prior.start)}–${shortDate(a.prior.end)}`:'Vergleich ausgeschaltet'}</span></div><div class="comparison-grid">${specs.map(([name,key,fmt])=>{const d=a.comparison[key];return `<article><span>${name}</span><strong>${fmt(a.summary[key])}</strong><p class="delta ${d.absolute==null?'':d.absolute>=0?'rise':'fall'}" data-testid="comparison-${key}">${a.previous?delta(key==='refundRate'?d.absolute:d.relative,key==='refundRate'?'pp':''):'—'}</p><small>Vorperiode ${fmt(a.previous?.summary[key]??null)}</small></article>`;}).join('')}</div><p class="table-note">DB nach zugeordneter Werbung, vor nicht zugeordneten Kontokosten. Fehlende Vorperioden bleiben unbekannt. Grün/Rot kennzeichnet die Richtung, nicht automatisch eine positive oder negative Geschäftsentwicklung.</p></section>`;
}
export function trendView(a,currency,metric='revenue') {
 const label={revenue:'Umsatz',profit:'Deckungsbeitrag',units:'Einheiten'}[metric],fmt=v=>metric==='units'?number(v):money(v,currency);
 const cur=a.series,old=a.previous?.series??[],values=[...cur,...old].map(d=>d[metric]).filter(v=>v!=null),min=Math.min(0,...values),max=Math.max(1,...values),range=max-min;
 const x=i=>50+(i/Math.max(1,cur.length-1))*860,y=v=>230-(v-min)/range*190;
 const path=rows=>{let pen=false;return rows.map((r,i)=>{const v=r[metric];if(v==null){pen=false;return '';}const command=pen?'L':'M';pen=true;return `${command}${x(i).toFixed(2)},${y(v).toFixed(2)}`;}).join(' ');};
 return `<section class="panel trend-panel"><div class="panel-heading"><div><p class="eyebrow">ENTWICKLUNG VERSTEHEN</p><h2>${label} im Zeitverlauf</h2></div><label>Kennzahl<select id="trend-metric" aria-label="Trend-Kennzahl">${Object.entries({revenue:'Umsatz',profit:'Deckungsbeitrag',units:'Einheiten'}).map(([key,name])=>`<option value="${key}" ${key===metric?'selected':''}>${name}</option>`).join('')}</select></label></div><div class="trend-shortcuts" role="group" aria-label="Trend auswählen">${Object.entries({revenue:'Umsatz',profit:'DB',units:'Einheiten'}).map(([key,name])=>`<button data-trend-metric="${key}" aria-pressed="${metric===key}">${name}</button>`).join('')}</div><div class="chart-legend"><span>● Auswahl</span>${a.previous?'<span>┄ Vorperiode · gleiche Anzahl Tage</span>':''}</div>
 <svg class="trend-chart" viewBox="0 0 950 275" role="img" aria-label="${label}: täglicher Verlauf und Vorperiode"><title>${label} · Tageswerte</title>${[0,.5,1].map(t=>{const v=min+range*t;return `<line x1="50" x2="910" y1="${y(v)}" y2="${y(v)}" stroke="#e4eae3"/><text x="45" y="${y(v)-7}" fill="#6d7d70" font-size="11">${metric==='units'?number(v):number(v)}${metric==='units'?'':` ${currency}`}</text>`;}).join('')}<path d="${path(old)}" fill="none" stroke="#98a795" stroke-width="2" stroke-dasharray="6 6"/><path d="${path(cur)}" fill="none" stroke="#315d40" stroke-width="3"/>${cur.map((r,i)=>r[metric]==null?'':`<circle cx="${x(i)}" cy="${y(r[metric])}" r="5" fill="#cfe5a7" stroke="#315d40" tabindex="0" role="button" data-trend-index="${i}" aria-label="${r.date}: ${esc(fmt(r[metric]))}"><title>${r.date}: ${esc(fmt(r[metric]))}</title></circle>`).join('')}<text x="50" y="265" font-size="12" fill="#6d7d70">${shortDate(a.options.start)}</text><text x="910" text-anchor="end" y="265" font-size="12" fill="#6d7d70">${shortDate(a.options.end)}</text></svg>
 <div class="trend-day-controls"><button id="trend-prev" aria-label="Vorheriger Tag">←</button><span>Tageswerte ansehen</span><button id="trend-next" aria-label="Nächster Tag">→</button></div><p id="trend-readout" aria-live="polite" class="table-note">Tagespunkte berühren oder mit der Tastatur fokussieren. Lücken bleiben sichtbar.</p><details class="trend-values"><summary>Tageswerte als Tabelle</summary><div class="table-scroll"><table><thead><tr><th>Datum</th><th>${label}</th><th>Vergleichsdatum</th><th>Vorperiode</th></tr></thead><tbody>${cur.map((r,i)=>`<tr><td>${r.date}</td><td>${fmt(r[metric])}</td><td>${old[i]?.date??'—'}</td><td>${fmt(old[i]?.[metric]??null)}</td></tr>`).join('')}</tbody></table></div></details></section>`;
}
export function insightsView(a) {
 return `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">VON ZAHLEN ZU FRAGEN</p><h2>Das verdient einen Blick</h2></div><span>Regelbasierte Hinweise · keine Ursachenbehauptung</span></div><div class="insight-grid">${a.insights.length?a.insights.slice(0,4).map(i=>`<article class="insight"><span class="insight-kind">${({quality:'Datenqualität',decline:'Umsatz',refunds:'Erstattungen',margin:'Marge',conversion:'Conversion'})[i.kind]}</span><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p><button ${i.productId?`data-product-open="${esc(i.productId)}"`:`data-jump-view="quality"`}>${i.productId?'Produkt untersuchen':'Datenabdeckung prüfen'} ↗</button></article>`).join(''):'<p class="table-note">Keine der definierten Schwellen ist in den verfügbaren Daten überschritten. Fehlende Daten sind keine Entwarnung.</p>'}</div></section>`;
}
export function productsView(a,currency,sort='revenue') {
 const ordered=[...a.products].sort((x,y)=>{const get=p=>sort==='growth'?p.change.relative:sort==='refunds'?p.refundRate:p[sort];const av=get(x),bv=get(y);return av==null?bv==null?x.name.localeCompare(y.name):1:bv==null?-1:bv-av;});
 return `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">EIN PRODUKT · ALLE KANÄLE</p><h2>Produktanalyse</h2></div><label>Sortierung<select id="product-sort" aria-label="Produkte sortieren">${Object.entries({revenue:'Umsatz',profit:'Deckungsbeitrag',growth:'Umsatzwachstum',refunds:'Erstattungsquote'}).map(([key,name])=>`<option value="${key}" ${key===sort?'selected':''}>${name} ↓</option>`).join('')}</select></label></div><p class="table-note">Zusammenführung über den internen Produktstamm, ohne SKU-Doppelzählung. Filter gelten für diese Tabelle. Marge und DB beziehen sich auf zugeordnete Kosten; ungeklärte Werte bleiben leer.</p><div class="sort-shortcuts" role="group" aria-label="Produkte ordnen">${Object.entries({revenue:'Umsatz',profit:'Deckungsbeitrag',growth:'Wachstum',refunds:'Erstattungen'}).map(([key,name])=>`<button data-product-sort="${key}" aria-pressed="${sort===key}">${name}</button>`).join('')}</div><div class="table-scroll" role="region" aria-label="Produktanalyse" tabindex="0"><table><thead><tr><th>Modell / Listings</th><th>Umsatz</th><th>Δ Vorperiode</th><th>Einheiten</th><th>Erstattungsquote</th><th>Deckungsbeitrag</th><th>Marge</th></tr></thead><tbody>${ordered.map(p=>`<tr data-testid="product-analysis-row"><td><button class="listing-link" data-product-open="${esc(p.id)}">${esc(p.name)} ↗</button><span class="subline">${esc(p.brandName)} · ${p.rows.length} Listings · ${new Set(p.rows.map(r=>r.account_id)).size} Kanäle</span></td><td>${money(p.revenue,currency)}</td><td>${delta(p.change.relative)}</td><td>${number(p.metrics.units)}</td><td>${pct(p.refundRate)}</td><td>${money(p.profit,currency)}</td><td>${pct(p.margin)}</td></tr>`).join('')}</tbody></table></div></section>`;
}
export function bridgeView(a,currency) {
 const b=a.costsBridge,steps=[['Nettoerlös nach Refunds',b.net],['Marktplatzgebühren',b.fees],['SKU-Kosten inkl. Fulfillment',b.unitCosts],['Zugeordnete Werbung',b.ads],['Deckungsbeitrag',b.profit]];
 return `<section class="panel"><div class="panel-heading"><h2>Vom Umsatz zum Deckungsbeitrag</h2><span>Netto · dieselbe Produktauswahl</span></div><div class="profit-bridge">${steps.map(([name,value],i)=>`<article><span>${i===0?'START':i===4?'ERGEBNIS':'ABZUG'}</span><strong>${money(value,currency)}</strong><small>${name}</small></article>`).join('')}</div><p class="table-note">Kein Unternehmensgewinn. Belegte Warenkosten-Rückbuchungen sind bereits im Ergebnis berücksichtigt. Unzugeordnete Kontokosten und allgemeine Betriebskosten werden hier nicht verteilt.</p></section>`;
}
export function qualityView(a,data) {
 return `<section class="panel"><div class="panel-heading"><h2>Wie belastbar ist diese Auswertung?</h2><span>Abdeckung der Auswahl · ausschließlich Demodaten</span></div><div class="quality-grid">${[['Umsatzdaten',a.coverage.sales,a.coverage.listings,'Listings mit vollständigen Tagesumsätzen'],['Profitdaten',a.coverage.profit,a.coverage.listings,'Listings mit berechenbarem Deckungsbeitrag'],['Werbekosten',a.marketing.spendCoverage,a.options.accountIds.length,'Kanäle mit vollständigem Spend'],['Attribution',a.marketing.attributionCoverage,a.options.accountIds.length,'Kanäle mit attribuiertem Umsatz']].map(([name,n,total,note])=>`<article><h3>${name}</h3><strong>${n} / ${total}</strong><progress value="${n}" max="${Math.max(1,total)}">${n} von ${total}</progress><p>${note}</p></article>`).join('')}</div><div class="notice"><strong>Keine echte Kontoverbindung.</strong> Dieser Datenstand stammt aus synthetischen Fixtures. Echte SKU-Mappings, aktuelle API-Berechtigungen, Quellenabgleich und historische FX-Kurse sind noch offen. Vollständige Demo-Daten bedeuten keine bestätigte Live-Datenqualität.</div><div class="table-scroll"><table><thead><tr><th>Kanal</th><th>Spend</th><th>Attribution</th><th>Nächster Prüfschritt</th></tr></thead><tbody>${a.marketing.channels.map(c=>`<tr><td>${esc(c.account.name)}</td><td>${c.spend==null?'Fehlt':'Demo vollständig'}</td><td>${c.adSales==null?'Fehlt / nicht vergleichbar':'Demo vorhanden'}</td><td class="catalog-description">${esc(c.issues.join(' · ')||'Mit echten Abrechnungen und Reports abgleichen.')}</td></tr>`).join('')}</tbody></table></div><p class="table-note">Verfügbare Demo-Historie: ${data.historyStart} bis ${data.end}. Vorperioden außerhalb dieses Bereichs werden nicht ergänzt oder geschätzt.</p></section>`;
}
export function productDetail(p,currency,data) {
 return `<div class="panel-heading"><div><p class="eyebrow">PRODUKT · ÜBER ALLE GEWÄHLTEN KANÄLE</p><h2 id="detail-title">${esc(p.name)}</h2></div><button id="close-detail" aria-label="Details schließen">Schließen ×</button></div><section class="metrics"><article class="metric"><p>Umsatz</p><strong>${money(p.revenue,currency)}</strong><small>${delta(p.change.relative)} zur Vorperiode</small></article><article class="metric"><p>Deckungsbeitrag</p><strong>${money(p.profit,currency)}</strong><small>Marge ${pct(p.margin)} · vor Kontokosten</small></article></section><p class="table-note">${p.issues.length?esc(p.issues.join(' · ')):'Alle benötigten Demo-Kosten vorhanden.'} Die Modellaggregation erfolgt über Listing-IDs, nicht über die Anzahl zugeordneter SKUs.</p><div class="table-scroll"><table><thead><tr><th>Kanal / Variante</th><th>Umsatz</th><th>Einheiten</th><th>Erstattungsquote</th><th>SKU-Zuordnung</th></tr></thead><tbody>${p.rows.map(r=>`<tr><td>${esc(data.accounts.find(a=>a.id===r.account_id).name.replace(' · Demo',''))}<span class="subline">${esc(r.title)}</span></td><td>${money(r.metrics.revenue_cents==null?null:r.metrics.revenue_cents/100,currency)}</td><td>${number(r.metrics.units)}</td><td>${pct(r.metrics.refundRate)}</td><td class="catalog-description">${r.skus.map(s=>esc(s.sku)).join(' · ')}</td></tr>`).join('')}</tbody></table></div><button id="product-to-listings" data-model="${esc(p.id)}">Dieses Modell in Listings öffnen</button>`;
}
export function bindIntelligence(a,currency,{trendMetric,onTrend,onSort,onProduct,onJump}) {
 document.querySelectorAll('[data-trend-metric]').forEach(b=>b.addEventListener('click',()=>onTrend(b.dataset.trendMetric)));
 document.querySelectorAll('[data-product-sort]').forEach(b=>b.addEventListener('click',()=>onSort(b.dataset.productSort)));
 document.querySelector('#trend-metric')?.addEventListener('change',e=>onTrend(e.target.value));
 document.querySelector('#product-sort')?.addEventListener('change',e=>onSort(e.target.value));
 document.querySelectorAll('[data-product-open]').forEach(b=>b.addEventListener('click',()=>onProduct(b.dataset.productOpen)));
 document.querySelectorAll('[data-jump-view]').forEach(b=>b.addEventListener('click',()=>onJump(b.dataset.jumpView)));
 let currentDay=0;
 const readout=document.querySelector('#trend-readout');
 const showDay=index=>{currentDay=Math.max(0,Math.min(a.series.length-1,index));const d=a.series[currentDay],old=a.previous?.series[currentDay],fmt=v=>trendMetric==='units'?number(v):money(v,currency);if(!d||!readout)return;readout.textContent=`${d.date}: ${fmt(d[trendMetric])} · Vorperiode ${old?.date??'—'}: ${fmt(old?.[trendMetric]??null)}`;document.querySelector('#trend-prev').disabled=currentDay===0;document.querySelector('#trend-next').disabled=currentDay===a.series.length-1;};
 document.querySelector('#trend-prev')?.addEventListener('click',()=>showDay(currentDay-1));document.querySelector('#trend-next')?.addEventListener('click',()=>showDay(currentDay+1));
 document.querySelector('.trend-chart')?.addEventListener('click',e=>{const r=e.currentTarget.getBoundingClientRect();showDay(Math.round((((e.clientX-r.left)/r.width)*950-50)/860*(a.series.length-1)));});
 for(const point of document.querySelectorAll('[data-trend-index]')){
  const show=()=>showDay(Number(point.dataset.trendIndex));
  point.addEventListener('pointerenter',show);point.addEventListener('focus',show);point.addEventListener('click',show);point.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show();}});
 }
 if(readout)showDay(0);
}
