const escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(v,c)=>v==null?'—':new Intl.NumberFormat('de-DE',{style:'currency',currency:c}).format(Number(v));
const percent=v=>v==null?'—':new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:1}).format(v);
const times=v=>v==null?'—':`${new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(v)}×`;
const card=(label,value,note,id)=>`<article class="metric"><p>${label}</p><strong data-testid="${id}">${value}</strong><small>${note}</small></article>`;
export function overviewView(report,{productFiltered=false}={}) {
 const {currency}=report;
 return `<section class="panel overview-intro"><div class="panel-heading"><h2>Gesamtüberblick · ${report.channels.length} Kanäle</h2><span>Kontoblick · gewählter Zeitraum</span></div><p class="table-note">Diese Übersicht folgt der Kanalauswahl und dem Zeitraum. Sie enthält den gesamten Spend inklusive nicht produktzuordenbarer Kosten. ${productFiltered?'<strong>Produkt-, Marken- und Suchfilter gelten weiter für die Listing-Auswertungen, nicht für diese Kontokennzahlen.</strong>':'Für einzelne Produkte unten zu Verkauf, Werbung oder Profit wechseln.'}</p></section>
 <section class="metrics" aria-label="Blended Werbekennzahlen">
 ${card('Blended ROAS / MER',times(report.mer),'Gesamtumsatz ÷ gesamter Spend','blended-roas')}
 ${card('Blended ACoS',percent(report.acos),'Gesamter Spend ÷ attribuierter Umsatz','blended-acos')}
 ${card('TACoS',percent(report.tacos),'Gesamter Spend ÷ Gesamtumsatz','blended-tacos')}
 ${card('Ads-ROAS · attribuiert',times(report.adsRoas),'Attribuierter Umsatz ÷ gesamter Spend','ads-roas')}
 </section><section class="metrics secondary">
 ${card('Gesamtumsatz · Kanäle',money(report.sales,currency),'Bestellumsatz vor Erstattungen, brutto','blended-sales')}
 ${card('Gesamter Werbespend',money(report.spend,currency),`${report.spendCoverage} / ${report.channels.length} Kanäle vollständig`,'blended-spend')}
 ${card('Attribuierter Umsatz',money(report.adSales,currency),`${report.attributionCoverage} / ${report.channels.length} Kanäle mit Attribution`,'blended-ad-sales')}
 </section>
 <div class="notice" role="status"><strong>Datenabdeckung: ${report.spendCoverage} / ${report.channels.length} Kanäle mit vollständigem Spend.</strong> ${report.spend==null?`Bekannter Spend vollständig vorliegender Kanäle: ${money(report.knownSpend,currency)}; keine Gesamtsumme für die Auswahl.`:'Alle ausgewählten Spend-Zeiträume sind abgedeckt.'} ${report.adSales==null?'Ads-ROAS und ACoS bleiben ohne vollständige, vergleichbare Attribution offen.':''} Es werden Summen dividiert, keine Kanalquoten gemittelt.</div>
 <section class="panel"><div class="panel-heading"><h2>Kanalvergleich</h2><span>Vom Gesamtblick zu den Listings</span></div><div class="table-scroll" role="region" aria-label="Kanalvergleich" tabindex="0"><table><thead><tr><th>Kanal</th><th>Umsatz</th><th>Spend</th><th>MER</th><th>ACoS</th><th>TACoS</th><th>Datenstand / Details</th></tr></thead><tbody>${report.channels.map(c=>`<tr data-testid="channel-comparison"><td><button class="listing-link" data-drill-channel="${escape(c.account.id)}" aria-label="${escape(c.account.name.replace(' · Demo',''))} einzeln analysieren">${escape(c.account.name.replace(' · Demo',''))} ↗</button></td><td><span title="Original: ${escape(money(c.original.sales,c.account.currency))}" tabindex="0" class="original-amount">${money(c.sales,currency)}</span></td><td><span title="Original: ${escape(money(c.original.spend,c.account.currency))}" tabindex="0" class="original-amount">${money(c.spend,currency)}</span></td><td>${times(c.mer)}</td><td>${percent(c.acos)}</td><td>${percent(c.tacos)}</td><td class="catalog-description"><details><summary>${c.issues.length?'Datenlücken ansehen':'Berechnung & Originalbeträge'}</summary><p>${escape(c.issues.join(' · ')||'Vollständige synthetische Beispielwerte.')}</p><p>Original: Umsatz ${money(c.original.sales,c.account.currency)}, Spend ${money(c.original.spend,c.account.currency)}, Ads-Umsatz ${money(c.original.adSales,c.account.currency)}.</p><p>Attribution: ${escape(c.attributionKey??'Nicht bestätigt')}. Kein deduplizierter, inkrementeller Umsatznachweis.</p></details></td></tr>`).join('')}</tbody></table></div></section>
 <details class="definitions"><summary>Definitionen, Attribution und Datenquellen</summary><p>Blended ROAS wird hier als Marketing Efficiency Ratio (MER) verwendet: gesamter Kanalumsatz durch gesamten Werbespend. TACoS ist die umgekehrte Quote. Ads-ROAS und ACoS verwenden ausschließlich den attribuierten Umsatz und sind ebenfalls Kehrwerte. Ein Nullnenner bleibt unbekannt.</p><p>Die Demo simuliert vergleichbare 14-Tage-Klickattribution für die Amazon-Konten. Das ist kein Nachweis eines einheitlichen realen SP/SB/SD/TV-Reports. eBay, OTTO und Kaufland besitzen hier weiterhin keine bestätigten Werbedaten. Unterschiedliche Fenster, Umsatzdefinitionen oder unvollständige Tage sperren die betroffenen Gesamtkennzahlen; MER/TACoS brauchen keine Ads-Attribution. Fehlende Werte sind keine Null.</p><p>Die Umsatzbasis ist brutto vor Refunds, Spend entspricht den berichteten Kosten. Spätere echte Quellen müssen Kostensteuerbasis, Attributionsfenster, Produktumfang, Zeitbezug und mögliche doppelte Umsatzzuordnung explizit abstimmen. EUR nutzt weiterhin synthetische Tageskurse.</p></details>`;
}
