import {esc,trendView,insightsView} from './intelligence.js';
const money=(v,c)=>v==null?'—':new Intl.NumberFormat('de-DE',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(v));
const number=v=>v==null?'—':new Intl.NumberFormat('de-DE').format(v);
const percent=v=>v==null?'—':new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:1}).format(v);
const delta=v=>v==null?'Nicht vergleichbar':`${v>=0?'+':''}${percent(v)}`;
const arrow='<span aria-hidden="true" class="action-arrow">→</span>';
export function homeView(a,currency,metric){
 const m=a.marketing,c=a.comparison;
 const tile=(label,value,note,target,id)=>`<button class="home-kpi" data-home-page="${target}"><span>${label}${arrow}</span><strong ${id?`data-testid="${id}"`:''}>${value}</strong><small>${note}</small></button>`;
 const products=[...a.products].sort((x,y)=>(y.revenue??-Infinity)-(x.revenue??-Infinity)).slice(0,3);
 return `<section class="home-kpis" aria-label="Geschäftskennzahlen – für Details antippen"><button class="home-kpi hero-kpi" data-home-page="products" aria-label="Umsatz nach Produkten aufschlüsseln" aria-describedby="home-revenue-value" title="${esc(m.channels.map(c=>`${c.account.name}: ${money(c.original.sales,c.account.currency)}`).join(' · '))}"><span>Umsatz${arrow}</span><strong id="home-revenue-value">${money(a.summary.revenue,currency)}</strong><div><span data-testid="comparison-revenue">${delta(c.revenue.relative)}</span><small>${a.previous?'zur Vorperiode':'Vergleich ausgeschaltet'}</small></div><small>Produkte ansehen</small></button>
 ${tile('Deckungsbeitrag',money(a.summary.profit,currency),a.summary.profit==null?'Kostenabdeckung prüfen':'Vor unzugeordneten Kontokosten','profit','home-profit')}
 ${tile('Verkaufte Einheiten',number(a.summary.units),'Listings & Traffic ansehen','sales','home-units')}
 ${tile('Werbeausgaben',money(m.spend,currency),`${m.spendCoverage}/${a.options.accountIds.length} Kanäle vollständig · Werbung öffnen`,'ads','home-spend')}
 ${tile('Erstattungsquote',percent(a.summary.refundRate),'Erstattungen aufschlüsseln','refunds','home-refunds')}</section>
 <section class="home-efficiency" aria-label="Werbeeffizienz">${[['Blended ROAS',m.mer==null?'—':`${new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(m.mer)}×`],['ACoS',percent(m.acos)],['TACoS',percent(m.tacos)]].map(([name,value])=>`<button data-home-page="markets"><span>${name}</span><strong>${value}</strong>${arrow}</button>`).join('')}</section>
 <button class="coverage-link" data-home-page="quality"><span class="coverage-dot ${m.spendCoverage<a.options.accountIds.length?'incomplete':''}"></span><span>${m.spendCoverage<a.options.accountIds.length?'Werbedaten unvollständig':'Datenbasis prüfen'} · ${a.options.accountIds.length} Kanäle</span>${arrow}</button>
 <div class="home-analysis"><section class="panel home-products"><div class="panel-heading"><div><h2>Deine Umsatztreiber</h2><p>Vom Modell bis zum Listing</p></div><button class="text-action" data-home-page="products">Alle ${a.products.length} ansehen →</button></div><div class="home-product-list">${products.map((p,i)=>`<button class="home-product" data-product-open="${esc(p.id)}" aria-label="${esc(p.name)} Produktdetails öffnen"><span class="product-rank">${i+1}</span><span class="product-identity"><strong>${esc(p.name)}</strong><small>${esc(p.brandName)} · ${p.rows.length} Listings</small></span><span class="product-values"><strong>${money(p.revenue,currency)}</strong><small>${delta(p.change.relative)}</small></span>${arrow}</button>`).join('')}</div></section>
 <div class="home-trend">${trendView(a,currency,metric)}</div></div>${insightsView(a)}`;
}
export function primaryNavigation(){return `<nav class="primary-navigation" aria-label="Schnellnavigation">${[['overview','Übersicht','▦'],['products','Produkte','▤'],['markets','Kanäle','◫']].map(([id,name,icon])=>`<button data-primary-page="${id}"><span aria-hidden="true">${icon}</span>${name}</button>`).join('')}<button id="more-navigation" aria-label="Weitere Bereiche öffnen" aria-controls="app-menu" aria-expanded="false"><span aria-hidden="true">☰</span>Mehr</button></nav>`;}
export function prepareMobileTables(root=document){for(const table of root.querySelectorAll('.table-scroll table')){if(table.closest('.trend-values'))continue;const headers=[...table.querySelectorAll('thead th')].map(th=>th.textContent);table.classList.add('mobile-stacked');for(const row of table.querySelectorAll('tbody tr'))[...row.children].forEach((cell,i)=>{cell.dataset.column=headers[i]??'';});}}
